spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobportal
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

djinni:
  credentials:
    email: yashar.gamidov@gmail.com
    password: "@Hemidzade179179"
  scraping:
    base-url: https://djinni.co
    dashboard-path: /my/dashboard/
    jobs-per-page: 25
    max-pages: 10  # Limit for demo purposes
    date-range: 90 # Days (3 months)

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    com:
      example:
        jobportal: DEBUG
  file:
    name: logs/job-portal.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

scheduling:
  job:
    scrape-djinni:
      cron: "0 0 12 * * *" # Daily at noon
      enabled: true